// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2UkG9Colca-wwL9lwNdwt_w1s-DJM6EQ',
    appId: '1:1083338064469:android:d0c8425952d2bd40ae0adc',
    messagingSenderId: '1083338064469',
    projectId: 'bonobono-fa1fb',
    storageBucket: 'bonobono-fa1fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI3DR9yvUPyr3I-07PQ88yIkKs_KVMP_k',
    appId: '1:1083338064469:ios:84f39cb24a168809ae0adc',
    messagingSenderId: '1083338064469',
    projectId: 'bonobono-fa1fb',
    storageBucket: 'bonobono-fa1fb.firebasestorage.app',
    iosBundleId: 'com.example.bonobono',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI3DR9yvUPyr3I-07PQ88yIkKs_KVMP_k',
    appId: '1:1083338064469:ios:84f39cb24a168809ae0adc',
    messagingSenderId: '1083338064469',
    projectId: 'bonobono-fa1fb',
    storageBucket: 'bonobono-fa1fb.firebasestorage.app',
    iosBundleId: 'com.example.bonobono',
  );
}
